engines:
  eslint:
    enabled: true
  duplication:
    enabled: false

ratings:
  paths:
  - client/**
  - server/**

exclude_paths:
  - client/__tests__/
  - client/dist/
  - server/test/
  - template/
