sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - postgresql

postgres:
  adapter: postgresql
  database: post-it test
  username: postgres
before_script:
  -  npm --prefix ./client install ./client
  - psql -c 'create database post-it test;' -U postgres
  - dropdb --if-exists post-it test && createdb post-it test
  - NODE_ENV=test npm run db:migrate
  - npm run test:server
