sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - postgresql

postgres:
  adapter: postgresql
  database: postit_test
  username: postgres
  
before_script:
  - psql -c 'create database postit_test;' -U postgres
  - npm install sequelize-cli -g

script:
  - npm run test:server

after_success:
  - npm run coveralls
