sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - postgresql

postgres:
  adapter: postgresql
  database: postit-test
  username: postgres
before_script:
  -  npm --prefix ./client install ./client
  - psql -c 'create database postit-test;' -U postgres
  - dropdb --if-exists postit-test && createdb postit-test
  - NODE_ENV=test npm run db:migrate
  - npm run test:server
